services:
  keycloak-service:
    build:
      context: docker
      dockerfile: keycloak.dockerfile
    command: >
      "/opt/keycloak/bin/kc.sh start-dev & 
       sleep 25 &&
      /home/keycloak.sh &&
       wait"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:9000/health/ready || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  mongodb-service:
    image: mongodb/mongodb-community-server:6.0.7-ubi8
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/shop",
          "--eval",
          "quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      keycloak-service:
        condition: service_healthy
  backend-service:
    build:
      dockerfile: docker/backend.dockerfile
    environment:
      web.url: "http://localhost"
      avatars.location: "/app/avatars"
      keycloak.uri: "http://keycloak-service:8080"
      keycloak.secret: "secret"
      mongo.uri: "mongodb://mongodb-service/shop"
    depends_on:
      keycloak-service:
        condition: service_healthy
      mongodb-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8080:8080"
  frontend:
    build:
      dockerfile: docker/frontend.dockerfile
      args:
        WEB_URL: "http://localhost"
        API_URL: "http://localhost:8080"
    ports:
      - "80:80"
    depends_on:
      backend-service:
        condition: service_healthy
