server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer}


  data:
    mongodb:
      uri: mongodb://localhost/shop

upload:
  avatarFolder: ${avatars.location}

keycloak:
  uri: http://localhost:8080
  realm: shop-realm
  client: shop-client
  secret: InQc3I2ocqiqRVXPYNSwUCBmxoveDUQo
  issuer: ${keycloak.uri}/realms/${keycloak.realm}

